# Generated by Django 5.2.17 on 2026-10-05 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('height', models.CharField(max_length=50, verbose_name='Рост')),
                ('nation', models.CharField(max_length=100, verbose_name='Кто она')),
                ('vibe', models.CharField(max_length=100, verbose_name='Вайб')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200, verbose_name='Услуга')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.profile', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Заметка')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.profile', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Услуга')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.profile', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
